---
#httpd_server_name: 'nexus.vm'
#httpd_setup_enable: true
#httpd_ssl_certificate_file: "{{ vault_httpd_ssl_certificate_file }}"
#httpd_ssl_certificate_key_file: "{{ vault_httpd_ssl_certificate_key_file }}"
